# Generated by Django 5.1 on 2024-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='car_images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
