# Generated by Django 5.1 on 2024-08-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_car_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='car',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
